const sections = [
  {
    title: "1. Acceptance of Terms",
    body: [
      "Welcome to AlignPod. These Terms of Use govern your access to and use of the AlignPod website, companion mobile application, wearable device, AI posture analysis services, and related features provided by AlignEye Vision Private Limited.",
      "By accessing or using our services, you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, please discontinue use of our services.",
    ],
  },
  {
    title: "2. About AlignPod",
    body: [
      "AlignPod is a smart posture and wellness platform designed to promote healthier posture habits through awareness, posture training, vibration therapy, AI-powered posture insights, and companion app features.",
      "AlignPod is intended for general wellness and educational purposes only.",
    ],
  },
  {
    title: "3. Eligibility",
    body: [
      "You must be legally capable of entering into a binding agreement under the laws applicable in your jurisdiction to use AlignPod.",
      "If you are under the applicable legal age, you should use AlignPod only with the supervision of a parent or legal guardian.",
    ],
  },
  {
    title: "4. Acceptable Use",
    body: [
      "You agree to use AlignPod only for lawful purposes.",
      "You must not misuse the device, mobile application, website, firmware, AI services, or attempt to interfere with their normal operation.",
      "Unauthorized modification, reverse engineering, tampering, or attempting to bypass device security is prohibited.",
    ],
  },
  {
    title: "5. User Accounts",
    body: [
      "Some features may require creating an account.",
      "You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account.",
    ],
  },
  {
    title: "6. AI Posture Analysis",
    body: [
      "AI posture analysis is provided solely for posture awareness and educational purposes.",
      "Results generated by AI are estimates and should not be considered professional medical advice or diagnosis.",
    ],
  },
  {
    title: "7. Training and Therapy Features",
    body: [
      "Training Mode provides vibration reminders intended to encourage healthier posture habits.",
      "Therapy Mode provides vibration-based wellness sessions intended to support relaxation and upper-back comfort.",
      "Users should discontinue use if discomfort occurs and consult an appropriate healthcare professional where necessary.",
    ],
  },
  {
    title: "8. Medical Disclaimer",
    body: [
      "AlignPod is not a medical device.",
      "It is not intended to diagnose, treat, cure, or prevent any disease or medical condition.",
      "Nothing provided through AlignPod should replace professional medical advice, diagnosis, or treatment.",
    ],
  },
  {
    title: "9. Intellectual Property",
    body: [
      "All software, firmware, product designs, graphics, branding, trademarks, logos, website content, documentation, and mobile applications remain the intellectual property of AlignEye Vision Private Limited.",
      "You may not reproduce, distribute, modify, or commercially exploit any part of AlignPod without prior written permission.",
    ],
  },
  {
    title: "10. Purchases and Orders",
    body: [
      "Prices, product availability, specifications, and promotions may change without prior notice.",
      "We reserve the right to refuse or cancel orders where necessary, including suspected fraudulent transactions.",
    ],
  },
  {
    title: "11. Warranty",
    body: [
      "Warranty coverage, if applicable, is governed by the separate Warranty Policy published on our website.",
      "Normal wear, accidental damage, misuse, unauthorized repairs, or modifications may void warranty coverage.",
    ],
  },
  {
    title: "12. Limitation of Liability",
    body: [
      "To the maximum extent permitted by applicable law, AlignEye Vision Private Limited shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from the use or inability to use AlignPod.",
      "Users assume responsibility for using the device safely and appropriately.",
    ],
  },
  {
    title: "13. Third-Party Services",
    body: [
      "Certain services may integrate with third-party providers including payment gateways, analytics providers, cloud services, or external websites.",
      "We are not responsible for the availability, content, or practices of third-party services.",
    ],
  },
  {
    title: "14. Termination",
    body: [
      "We reserve the right to suspend or terminate access to our services where these Terms of Use are violated or where necessary to protect our users, products, or business.",
    ],
  },
  {
    title: "15. Changes to These Terms",
    body: [
      "These Terms of Use may be updated from time to time.",
      "Continued use of AlignPod after changes become effective constitutes acceptance of the updated Terms.",
    ],
  },
  {
    title: "16. Governing Law",
    body: [
      "These Terms of Use shall be governed by and interpreted in accordance with the laws of India.",
      "Any disputes arising from these terms shall be subject to the jurisdiction of the competent courts.",
    ],
  },
  {
    title: "17. Contact Us",
    body: [
      "If you have any questions regarding these Terms of Use, please contact us:",
      "AlignEye Vision Private Limited",
      "Email: support@aligneye.com",
      "Website: https://www.aligneye.com",
    ],
  },
];

export function TermsOfUse() {
  return (
    <main className="min-h-screen bg-[#F8F8F6] pt-28 px-6">
      <section className="max-w-5xl mx-auto py-16 lg:py-24">
        <div className="text-center mb-14">
          <p className="text-sm tracking-[0.25em] uppercase text-gray-500 mb-4">
            Legal
          </p>

          <h1 className="text-5xl md:text-7xl font-semibold text-[#111111] mb-6">
            Terms of Use
          </h1>

          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            These Terms of Use explain the rules, responsibilities, and conditions for using AlignPod, our website, companion application, and related services.
          </p>

          <p className="text-sm text-gray-500 mt-6">
            Last Updated: July 2026
          </p>
        </div>

        <div className="bg-white rounded-[36px] border border-gray-200 shadow-sm p-6 md:p-12 lg:p-14">
          <div className="space-y-10">
            {sections.map((section) => (
              <section key={section.title}>
                <h2 className="text-2xl md:text-3xl font-semibold text-[#111111] mb-4">
                  {section.title}
                </h2>

                <div className="space-y-4 text-gray-600 leading-relaxed text-base md:text-lg">
                  {section.body.map((paragraph, index) => (
                    <p key={index}>{paragraph}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>

          <div className="mt-14 rounded-[28px] bg-[#F8F8F6] border border-gray-200 p-6 md:p-8">
            <p className="text-sm text-gray-500 leading-relaxed">
              These Terms of Use are intended to provide a clear understanding of your rights and responsibilities when using AlignPod. We recommend reviewing these terms periodically, as they may be updated to reflect new features, services, or legal requirements.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}